version: '3'

tasks:
  format:
    desc: "Format code with black and isort"
    cmds:
      - black .
      - isort .

  lint:
    desc: "Lint code using Ruff (includes flake8 + more)"
    cmds:
      - ruff check .

  fix:
    desc: "Auto-fix lint issues with Ruff"
    cmds:
      - ruff check . --fix

  test:
    desc: "Run pytest unit tests"
    cmds:
      - pytest

  quality:
    desc: "Run all quality checks"
    cmds:
      - task format
      - task lint
      - task test

  run:
    desc: "Run the FastAPI app"
    cmds:
      - uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  task:
    desc: "Run task inside Docker"
    cmds:
      - docker run --rm -v $PWD:/app -w /app python:3.11-slim bash -c "pip install poetry && poetry install && poetry run task quality"

