version: '3'

tasks:
  format:
    desc: "Format code with ruff"
    cmds:
      - poetry run ruff format .

  lint:
    desc: "Lint code and auto-fix using Ruff (includes flake8 + more)"
    cmds:
      - poetry run ruff check . --fix

  test:
    desc: "Run pytest unit tests"
    cmds:
      - poetry run pytest

  quality:
    desc: "Run all quality checks"
    cmds:
      - task format
      - task lint
      - task test

  clean_docker:
    desc: "Clean reclaimable docker images"
    cmds:
      - sudo docker image prune -a -f

  run:
    desc: "Run the FastAPI app"
    cmds:
      - uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  task:
    desc: "Run task inside Docker"
    cmds:
      - docker run --rm -v $PWD:/app -w /app python:3.11-slim bash -c "pip install poetry && poetry install && poetry run task quality"


