name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python3

      - name: Configure Poetry in PATH
        run: echo "PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV

      - name: Run formatter and linter
        run: |
          poetry run python -m black .
          poetry run python -m isort .
          poetry run python -m ruff .

      - name: Run tests
        run: poetry run pytest

