name: Deploy to Railway

on:
  workflow_run:
    workflows: ["CI"]      # Must match the `name:` of the CI workflow
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    env:
      SVC_ID: 627d4d74-7088-4da6-aeb3-ac409fd64775
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - run: railway up --service=${{ env.SVC_ID }}